"use client"

/**
 * AnonymizeSettings — panneau de personnalisation des CV anonymisés, au POINT
 * D'USAGE (shortlist d'une mission). Ouvert à TOUT sourceur disposant d'un
 * siège actif : l'anonymisation n'est plus réservée à l'owner via Branding.
 *
 * Deux portées :
 *   - GABARIT DE L'ORGANISATION (template + filigrane) : présentation commune à
 *     tous les CV. Réglable ici, enregistré via /api/organization/anonymize-defaults
 *     (n'importe quel siège). Bouton « Enregistrer le gabarit ».
 *   - POUR CETTE MISSION (résumé Nora + message) : contenu éditorial, propre à
 *     la mission. Auto-sauvé par le parent (PATCH /api/jobs/:id).
 *
 * Composant CONTRÔLÉ : les valeurs vivent dans la shortlist parent, pour que
 * « ce que vous voyez == ce que vous téléchargez » (les téléchargements passent
 * ces mêmes valeurs en surcharge live à la génération).
 *
 * Aides visuelles : aperçu HTML instantané (squelette de CV) + « Télécharger un
 * exemple » (vrai PDF via /api/cabinet/anonymize-sample, sans quota ni stockage).
 */

import { useRef, useState } from "react"
import {
  type AnonymizeTemplate, TEMPLATE_META, TEMPLATE_META_EN,
} from "@/components/workspace/anonymize/types"
import type { Lang } from "@/lib/i18n/LanguageContext"

const HEX = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/

const copy = {
  fr: {
    orgTitle: "Gabarit de l'organisation",
    orgSubtitle: "Modèle + filigrane appliqués à tous vos CV anonymisés. Modifiable par toute l'équipe.",
    missionTitle: "Pour cette mission",
    templateLabel: "Modèle",
    watermarkLabel: "Filigrane de protection",
    watermarkHint: "Imprime votre nom en diagonale sur toutes les pages — décourage la réutilisation du CV sans passer par vous.",
    watermarkTextLabel: "Texte du filigrane",
    watermarkPlaceholder: "Nom de votre organisation",
    anonNora: "Inclure le résumé Nora",
    anonNoraHint: "Un résumé factuel du profil orienté mission, généré par Nora. Décoché par défaut.",
    anonMessage: "Message sur le CV (optionnel)",
    anonMessagePlaceholder: "ex : Profil présenté pour votre mission…",
    save: "Enregistrer le gabarit",
    saving: "Enregistrement…",
    saved: "Gabarit enregistré",
    downloadSample: "Télécharger un exemple",
    generating: "Génération…",
    previewLabel: "Aperçu · exemple",
    previewNote: "Aperçu indicatif. Téléchargez l'exemple pour le rendu exact.",
    error: "Une erreur est survenue. Réessayez.",
    sampleSkills: "Compétences",
    sampleExp: "Expérience",
    presentedFor: "Présenté pour",
    missionName: "Nom de la mission",
    metaSeniority: "Séniorité",
    metaExperience: "Expérience",
    metaZone: "Zone",
    metaLanguages: "Langues",
    sectionEducation: "Formation",
    brandingLink: "Gérer l'identité de l'organisation",
  },
  en: {
    orgTitle: "Organization template",
    orgSubtitle: "Template + watermark applied to all your anonymized CVs. Editable by the whole team.",
    missionTitle: "For this mission",
    templateLabel: "Template",
    watermarkLabel: "Protection watermark",
    watermarkHint: "Prints your name diagonally across every page — discourages reuse of the CV without going through you.",
    watermarkTextLabel: "Watermark text",
    watermarkPlaceholder: "Your organization name",
    anonNora: "Include the Nora summary",
    anonNoraHint: "A factual, mission-oriented summary of the profile, generated by Nora. Off by default.",
    anonMessage: "Message on the CV (optional)",
    anonMessagePlaceholder: "e.g. Profile presented for your mission…",
    save: "Save template",
    saving: "Saving…",
    saved: "Template saved",
    downloadSample: "Download a sample",
    generating: "Generating…",
    previewLabel: "Preview · sample",
    previewNote: "Indicative preview. Download the sample for the exact rendering.",
    error: "Something went wrong. Please try again.",
    sampleSkills: "Skills",
    sampleExp: "Experience",
    presentedFor: "Presented for",
    missionName: "Mission name",
    metaSeniority: "Seniority",
    metaExperience: "Experience",
    metaZone: "Location",
    metaLanguages: "Languages",
    sectionEducation: "Education",
    brandingLink: "Manage the organization identity",
  },
}

export interface AnonymizeBranding {
  orgName: string
  logoUrl: string | null
  color: string | null
  colorSecondary: string | null
  slogan: string | null
  contactEmail: string | null
}

interface Props {
  branding: AnonymizeBranding
  /** Gabarit org (contrôlé). */
  template: AnonymizeTemplate
  watermark: boolean
  watermarkText: string
  onTemplate: (v: AnonymizeTemplate) => void
  onWatermark: (v: boolean) => void
  onWatermarkText: (v: string) => void
  /** Options mission (contrôlé). */
  keepNoraSummary: boolean
  customText: string
  onKeepNora: (v: boolean) => void
  onCustomText: (v: string) => void
  /** Lien vers l'onglet Branding (owner/délégué) — null = masqué. */
  brandingHref?: string | null
  lang: Lang
}

export function AnonymizeSettings(props: Props) {
  const {
    branding, template, watermark, watermarkText,
    onTemplate, onWatermark, onWatermarkText,
    keepNoraSummary, customText, onKeepNora, onCustomText,
    brandingHref, lang,
  } = props
  const t = copy[lang]
  const meta = lang === "fr" ? TEMPLATE_META : TEMPLATE_META_EN
  const orgName = branding.orgName

  const [busy, setBusy] = useState<"idle" | "saving" | "sample">("idle")
  const [saved, setSaved] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const savedTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  const accent = branding.color && HEX.test(branding.color) ? branding.color : "#111827"
  const accentSecondary = branding.colorSecondary && HEX.test(branding.colorSecondary) ? branding.colorSecondary : accent
  const effectiveWatermark = (watermarkText.trim() || orgName || "").toUpperCase()

  const gabaritPayload = () => ({ template, watermark, watermarkText: watermarkText.trim().slice(0, 40) })

  async function saveGabarit() {
    setBusy("saving"); setError(null)
    try {
      const res = await fetch("/api/organization/anonymize-defaults", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(gabaritPayload()),
      })
      if (!res.ok) throw new Error("save_failed")
      setSaved(true)
      if (savedTimer.current) clearTimeout(savedTimer.current)
      savedTimer.current = setTimeout(() => setSaved(false), 2500)
    } catch {
      setError(t.error)
    } finally {
      setBusy("idle")
    }
  }

  async function downloadSample() {
    setBusy("sample"); setError(null)
    try {
      const res = await fetch("/api/cabinet/anonymize-sample", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ anonymize_defaults: gabaritPayload() }),
      })
      if (!res.ok) throw new Error("sample_failed")
      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = "exemple-cv-anonymise.pdf"
      document.body.appendChild(a); a.click(); a.remove()
      URL.revokeObjectURL(url)
    } catch {
      setError(t.error)
    } finally {
      setBusy("idle")
    }
  }

  return (
    <div style={{
      borderRadius: 14, border: "1px solid var(--nw-border)", background: "white",
      padding: "18px 18px 20px",
    }}>
      <div style={{ display: "grid", gap: 22, gridTemplateColumns: "minmax(0, 1fr) minmax(0, 360px)", alignItems: "start" }}>
        {/* Réglages */}
        <div style={{ display: "flex", flexDirection: "column", gap: 20, minWidth: 0 }}>
          {/* Gabarit org */}
          <div>
            <SectionHead title={t.orgTitle} subtitle={t.orgSubtitle} />
            <div style={{ marginTop: 12 }}>
              <label style={fieldLabel}>{t.templateLabel}</label>
              <div style={{ display: "grid", gap: 8, gridTemplateColumns: "1fr 1fr", marginTop: 8 }}>
                {(Object.keys(meta) as AnonymizeTemplate[]).map((k) => {
                  const on = template === k
                  return (
                    <button
                      key={k}
                      type="button"
                      onClick={() => onTemplate(k)}
                      style={{
                        textAlign: "left", fontFamily: "inherit", cursor: "pointer",
                        padding: "10px 12px", borderRadius: 10,
                        border: `1.5px solid ${on ? "var(--nw-primary)" : "var(--nw-border)"}`,
                        background: on ? "var(--nw-primary-50)" : "white",
                      }}
                    >
                      <span style={{ display: "block", fontSize: 12.5, fontWeight: 700, color: on ? "var(--nw-primary)" : "var(--nw-text)" }}>
                        {meta[k].label}
                      </span>
                      <span style={{ display: "block", fontSize: 10.5, color: "var(--nw-text-muted)", marginTop: 2, lineHeight: 1.4 }}>
                        {meta[k].hint}
                      </span>
                    </button>
                  )
                })}
              </div>
            </div>

            {/* Filigrane */}
            <div style={{ marginTop: 16 }}>
              <label style={{ display: "flex", alignItems: "flex-start", gap: 10, cursor: "pointer" }}>
                <input
                  type="checkbox"
                  checked={watermark}
                  onChange={(e) => onWatermark(e.target.checked)}
                  style={{ marginTop: 2, width: 16, height: 16, accentColor: "var(--nw-primary)" }}
                />
                <span>
                  <span style={{ display: "block", fontSize: 13, fontWeight: 700, color: "var(--nw-text)" }}>{t.watermarkLabel}</span>
                  <span style={{ display: "block", fontSize: 11.5, color: "var(--nw-text-muted)", marginTop: 2, lineHeight: 1.5 }}>{t.watermarkHint}</span>
                </span>
              </label>
              {watermark && (
                <div style={{ marginTop: 10, paddingLeft: 26 }}>
                  <label style={fieldLabel}>{t.watermarkTextLabel}</label>
                  <input
                    type="text"
                    value={watermarkText}
                    onChange={(e) => onWatermarkText(e.target.value.slice(0, 40))}
                    placeholder={orgName || t.watermarkPlaceholder}
                    style={inputStyle}
                  />
                </div>
              )}
            </div>

            <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", marginTop: 14 }}>
              <button type="button" onClick={saveGabarit} disabled={busy !== "idle"} style={btnPrimary(busy === "saving")}>
                {busy === "saving" ? t.saving : t.save}
              </button>
              <button type="button" onClick={downloadSample} disabled={busy !== "idle"} style={btnGhost(busy === "sample")}>
                {busy === "sample" ? t.generating : t.downloadSample}
              </button>
              {saved && <span style={{ fontSize: 12, fontWeight: 600, color: "var(--nw-success)" }}>{t.saved}</span>}
              {error && <span style={{ fontSize: 12, color: "var(--nw-danger-strong, #B91C1C)" }}>{error}</span>}
            </div>
          </div>

          {/* Options mission */}
          <div style={{ borderTop: "1px solid var(--nw-border)", paddingTop: 16 }}>
            <SectionHead title={t.missionTitle} />
            <label style={{ display: "flex", alignItems: "flex-start", gap: 10, cursor: "pointer", marginTop: 12 }}>
              <input
                type="checkbox"
                checked={keepNoraSummary}
                onChange={(e) => onKeepNora(e.target.checked)}
                style={{ marginTop: 2, width: 16, height: 16, accentColor: "var(--nw-primary)" }}
              />
              <span>
                <span style={{ display: "block", fontSize: 13, fontWeight: 700, color: "var(--nw-text)" }}>{t.anonNora}</span>
                <span style={{ display: "block", fontSize: 11.5, color: "var(--nw-text-muted)", marginTop: 2, lineHeight: 1.5 }}>{t.anonNoraHint}</span>
              </span>
            </label>
            <div style={{ marginTop: 12 }}>
              <label style={fieldLabel}>{t.anonMessage}</label>
              <input
                type="text"
                value={customText}
                onChange={(e) => onCustomText(e.target.value.slice(0, 600))}
                placeholder={t.anonMessagePlaceholder}
                style={inputStyle}
              />
            </div>
            {brandingHref && (
              <a href={brandingHref} style={{
                display: "inline-flex", alignItems: "center", gap: 6, marginTop: 14,
                fontSize: 12, fontWeight: 600, color: "var(--nw-primary)", textDecoration: "none",
              }}>
                {t.brandingLink}
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                  <path d="M5 12h14M13 6l6 6-6 6" />
                </svg>
              </a>
            )}
          </div>
        </div>

        {/* Aperçu */}
        <div style={{ minWidth: 0 }}>
          <label style={fieldLabel}>{t.previewLabel}</label>
          <div style={{ marginTop: 10 }}>
            <MiniPreview
              accent={accent}
              accentSecondary={accentSecondary}
              logoUrl={branding.logoUrl}
              orgName={orgName}
              slogan={branding.slogan}
              contactEmail={branding.contactEmail}
              watermark={watermark}
              watermarkText={effectiveWatermark}
              template={template}
              t={t}
            />
            <p style={{ margin: "8px 0 0", fontSize: 11, color: "var(--nw-text-muted)", lineHeight: 1.5 }}>{t.previewNote}</p>
          </div>
        </div>
      </div>
    </div>
  )
}

/* ── Aperçu HTML représentatif (squelette de CV, pas le PDF exact) ─────────── */

const SKEL = "#E5E7EB"
const CHIP_WIDTHS = [62, 82, 48, 68, 56, 44]

function MiniPreview({
  accent, accentSecondary, logoUrl, orgName, slogan, contactEmail, watermark, watermarkText, template, t,
}: {
  accent: string
  accentSecondary: string
  logoUrl: string | null
  orgName: string
  slogan: string | null
  contactEmail: string | null
  watermark: boolean
  watermarkText: string
  template: AnonymizeTemplate
  t: (typeof copy)["fr"]
}) {
  const bar = (w: number | string, h = 7, mb = 7, color = SKEL) => (
    <div style={{ width: typeof w === "number" ? `${w}%` : w, height: h, borderRadius: 3, background: color, marginBottom: mb }} />
  )
  const secLabel = (label: string) => (
    <p style={{ margin: "0 0 8px", fontSize: 10, fontWeight: 800, color: accentSecondary, textTransform: "uppercase", letterSpacing: 0.8 }}>{label}</p>
  )
  const chips = () => (
    <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
      {CHIP_WIDTHS.map((w, i) => (
        <div key={i} style={{ width: w, height: 15, borderRadius: 20, background: "#F0F1F4" }} />
      ))}
    </div>
  )
  // Entrées volontairement compactes : l'aperçu doit TENIR dans l'A4 (overflow
  // masqué) sur tous les templates, sans jamais couper le dernier bloc.
  const expEntry = (key: number) => (
    <div key={key} style={{ marginBottom: 10 }}>
      {bar(52, 8, 5, "#CBD0D8")}
      {bar(34, 6, 6, "#E5E7EB")}
      {bar(94, 6, 0)}
    </div>
  )
  const eduEntry = (key: number) => (
    <div key={key} style={{ marginBottom: 8 }}>
      {bar(50, 8, 4, "#CBD0D8")}
      {bar(32, 6, 0, "#E5E7EB")}
    </div>
  )
  const metaField = (label: string) => (
    <div style={{ minWidth: 0 }}>
      <p style={{ margin: "0 0 5px", fontSize: 8.5, fontWeight: 700, color: "#9CA3AF", textTransform: "uppercase", letterSpacing: 0.4 }}>{label}</p>
      {bar("74%", 8, 0, "#CBD0D8")}
    </div>
  )
  const missionTitle = (size: number, center = false) => (
    <>
      <p style={{ margin: 0, fontSize: 9.5, fontWeight: 700, color: "#9CA3AF", textTransform: "uppercase", letterSpacing: 0.8, textAlign: center ? "center" : "left" }}>{t.presentedFor}</p>
      <p style={{ margin: "5px 0 0", fontSize: size, fontWeight: 800, color: "#9CA3AF", fontStyle: "italic", textAlign: center ? "center" : "left" }}>
        {t.missionName}
      </p>
    </>
  )
  const metaRow = () => (
    <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 10, marginTop: 14 }}>
      {metaField(t.metaSeniority)}{metaField(t.metaExperience)}{metaField(t.metaZone)}{metaField(t.metaLanguages)}
    </div>
  )

  let body: React.ReactNode
  if (template === "two-column") {
    body = (
      <>
        {missionTitle(18)}
        <div style={{ display: "grid", gridTemplateColumns: "36% 1fr", gap: 14, marginTop: 14 }}>
          <div style={{ background: "#FAFAFC", borderRadius: 6, padding: "11px 11px" }}>
            <div style={{ display: "flex", flexDirection: "column", gap: 12, marginBottom: 16 }}>
              {metaField(t.metaSeniority)}{metaField(t.metaExperience)}{metaField(t.metaLanguages)}
            </div>
            {secLabel(t.sampleSkills)}{chips()}
          </div>
          <div>
            {secLabel(t.sampleExp)}{[0, 1, 2].map(expEntry)}
            <div style={{ marginTop: 4 }}>{secLabel(t.sectionEducation)}{[0, 1].map(eduEntry)}</div>
          </div>
        </div>
      </>
    )
  } else if (template === "executive") {
    body = (
      <div>
        <div style={{ textAlign: "center" }}>
          {missionTitle(22, true)}
          <div style={{ width: 54, height: 3, background: accent, margin: "10px auto" }} />
        </div>
        <div style={{ maxWidth: 280, margin: "0 auto" }}>
          {metaRow()}
          <div style={{ marginTop: 14 }}>{secLabel(t.sampleSkills)}{chips()}</div>
          <div style={{ marginTop: 14 }}>{secLabel(t.sampleExp)}{[0, 1, 2].map(expEntry)}</div>
          <div style={{ marginTop: 10 }}>{secLabel(t.sectionEducation)}{[0, 1].map(eduEntry)}</div>
        </div>
      </div>
    )
  } else if (template === "bento") {
    const cardBox: React.CSSProperties = { border: "1px solid #ECECF1", borderRadius: 8, padding: "10px 11px", background: "white" }
    body = (
      <>
        {missionTitle(18)}
        {metaRow()}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginTop: 12 }}>
          <div style={cardBox}>{secLabel(t.sampleSkills)}{chips()}</div>
          <div style={cardBox}>{secLabel(t.sectionEducation)}{[0, 1].map(eduEntry)}</div>
          <div style={{ ...cardBox, gridColumn: "1 / -1" }}>{secLabel(t.sampleExp)}{[0, 1, 2].map(expEntry)}</div>
        </div>
      </>
    )
  } else {
    body = (
      <>
        {missionTitle(20)}
        {metaRow()}
        <div style={{ marginTop: 14 }}>{secLabel(t.sampleSkills)}{chips()}</div>
        <div style={{ marginTop: 14 }}>{secLabel(t.sampleExp)}{[0, 1, 2].map(expEntry)}</div>
        <div style={{ marginTop: 8 }}>{secLabel(t.sectionEducation)}{[0, 1].map(eduEntry)}</div>
      </>
    )
  }

  return (
    <div style={{
      position: "relative", overflow: "hidden",
      marginTop: 4, background: "white",
      border: "1px solid var(--nw-border)", borderRadius: 10,
      boxShadow: "0 6px 20px rgba(17,24,39,0.08)",
      aspectRatio: "1 / 1.414", minHeight: 300,
      display: "flex", flexDirection: "column",
      fontSize: 8.5, color: "#1F2937",
    }}>
      {watermark && watermarkText && (
        <div aria-hidden style={{
          position: "absolute", inset: 0, zIndex: 2, pointerEvents: "none",
          display: "flex", alignItems: "center", justifyContent: "center",
        }}>
          <span style={{
            transform: "rotate(-32deg)", whiteSpace: "nowrap",
            fontSize: 20, fontWeight: 800, letterSpacing: 2,
            color: accent, opacity: 0.07, textTransform: "uppercase",
          }}>
            {watermarkText}&nbsp;&nbsp;{watermarkText}
          </span>
        </div>
      )}

      <div style={{
        borderTop: `4px solid ${accent}`, padding: "10px 12px 8px",
        display: "flex", alignItems: "center", gap: 8,
        borderBottom: "1px solid #F1F1F4",
      }}>
        {logoUrl ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={logoUrl} alt="" style={{ height: 18, maxWidth: 70, objectFit: "contain" }} />
        ) : orgName ? (
          <span style={{ fontSize: 10, fontWeight: 800, color: accent }}>{orgName}</span>
        ) : null}
        <span style={{
          marginLeft: "auto", fontSize: 6.5, fontWeight: 700, letterSpacing: 0.5,
          color: "#9CA3AF", textTransform: "uppercase",
        }}>
          C-000000
        </span>
      </div>

      <div style={{ flex: 1, padding: "12px 14px", minHeight: 0, position: "relative", zIndex: 1 }}>
        {body}
      </div>

      <div style={{
        borderTop: "1px solid #F1F1F4", padding: "6px 12px",
        display: "flex", alignItems: "center", gap: 6,
        fontSize: 6.5, color: "#6B7280",
      }}>
        {orgName && <span style={{ fontWeight: 700, color: accent }}>{orgName}</span>}
        {contactEmail && <span>· {contactEmail}</span>}
        {slogan && <span style={{ marginLeft: "auto", fontStyle: "italic" }}>{slogan}</span>}
      </div>
    </div>
  )
}

/* ── Bricoles ─────────────────────────────────────────────────────────── */

const fieldLabel: React.CSSProperties = {
  fontSize: 10.5, fontWeight: 700, letterSpacing: "0.06em", textTransform: "uppercase",
  color: "var(--nw-text-muted)", fontFamily: "var(--nw-font-mono)",
}

const inputStyle: React.CSSProperties = {
  marginTop: 6, width: "100%", boxSizing: "border-box",
  padding: "8px 11px", fontSize: 13, fontFamily: "inherit", color: "var(--nw-text)",
  background: "white", border: "1px solid var(--nw-border)", borderRadius: 8, outline: "none",
}

function btnPrimary(loading: boolean): React.CSSProperties {
  return {
    fontFamily: "inherit", fontSize: 13, fontWeight: 700, color: "white",
    background: "var(--nw-primary)", border: "none", borderRadius: 9,
    padding: "9px 16px", cursor: loading ? "wait" : "pointer", opacity: loading ? 0.7 : 1,
  }
}
function btnGhost(loading: boolean): React.CSSProperties {
  return {
    fontFamily: "inherit", fontSize: 13, fontWeight: 600, color: "var(--nw-primary)",
    background: "white", border: "1px solid var(--nw-primary)", borderRadius: 9,
    padding: "9px 16px", cursor: loading ? "wait" : "pointer", opacity: loading ? 0.7 : 1,
  }
}

function SectionHead({ title, subtitle }: { title: string; subtitle?: string }) {
  return (
    <div>
      <h4 style={{ margin: 0, fontSize: 13.5, fontWeight: 800, color: "var(--nw-text)", letterSpacing: "-0.01em" }}>{title}</h4>
      {subtitle && <p style={{ margin: "3px 0 0", fontSize: 11.5, color: "var(--nw-text-muted)", lineHeight: 1.5 }}>{subtitle}</p>}
    </div>
  )
}
